repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/regebro/pyroma
    rev: "5.0.1"
    hooks:
      - id: pyroma
        args: ["--min=10", "."]
