---
ci:
  skip:
    - actionlint
    - shellcheck
    - shellcheck-docs
    - shfmt
    - shfmt-docs
    - pyright-verifytypes
    - pyright-docs
    - check-manifest
    - deptry
    - pyproject-fmt

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
      - id: rst-backticks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/regebro/pyroma
    rev: 5.0.1
    hooks:
      - id: pyroma
        args: [--min=10, .]
  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: uv run --extra=dev actionlint
        language: python
        pass_filenames: false
        types_or: [yaml]
        additional_dependencies: [uv==0.9.5]

      - id: shellcheck
        name: shellcheck
        entry: uv run --extra=dev shellcheck --shell=bash
        language: python
        types_or: [shell]
        additional_dependencies: [uv==0.9.5]

      - id: shellcheck-docs
        name: shellcheck-docs
        entry: uv run --extra=dev doccmd --no-write-to-file --example-workers 0 --language=shell
          --language=console --command="shellcheck --shell=bash"
        language: python
        types_or: [markdown, rst]
        additional_dependencies: [uv==0.9.5]

      - id: shfmt
        name: shfmt
        entry: uv run --extra=dev shfmt --write --space-redirects --indent=4
        language: python
        types_or: [shell]
        additional_dependencies: [uv==0.9.5]

      - id: shfmt-docs
        name: shfmt-docs
        entry: uv run --extra=dev doccmd --language=shell --language=console --skip-marker=shfmt
          --no-pad-file --command="shfmt --write --space-redirects --indent=4"
        language: python
        types_or: [markdown, rst]
        additional_dependencies: [uv==0.9.5]

      - id: doc8
        name: doc8
        entry: uv run --extra=dev doc8 docs/source/
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: interrogate
        name: interrogate
        entry: uv run --extra=dev interrogate -v src/ tests/
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: pydocstringformatter
        name: pydocstringformatter
        entry: uv run --extra=dev pydocstringformatter src/ tests/
        language: python
        pass_filenames: false
        types: [python]
        additional_dependencies: [uv==0.9.5]

      - id: vulture
        name: vulture
        entry: uv run --extra=dev vulture src/
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: yamlfix
        name: yamlfix
        entry: uv run --extra=dev yamlfix
        language: python
        types: [yaml]
        additional_dependencies: [uv==0.9.5]

      - id: pyproject-fmt
        name: pyproject-fmt
        entry: uv run --extra=dev pyproject-fmt
        language: python
        types_or: [toml]
        files: pyproject.toml
        additional_dependencies: [uv==0.9.5]

      - id: check-manifest
        name: check-manifest
        entry: uv run --extra=dev -m check_manifest
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: deptry
        name: deptry
        entry: uv run --extra=dev -m deptry src/
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: pyright-verifytypes
        name: pyright verifytypes
        entry: uv run --extra=dev -m pyright --ignoreexternal --verifytypes openapi_mock
        language: python
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: pyright-docs
        name: pyright-docs
        entry: uv run --extra=dev doccmd --no-write-to-file --example-workers 0 --language=python
          --command="pyright"
        language: python
        types_or: [markdown, rst]
        additional_dependencies: [uv==0.9.5]

      - id: linkcheck
        name: linkcheck
        entry: uv run --extra=dev sphinx-build -M linkcheck docs/source docs/build
          -W
        language: python
        types_or: [rst]
        stages: [manual]
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: spelling
        name: spelling
        entry: uv run --extra=dev sphinx-build -M spelling docs/source docs/build
          -W
        language: python
        types_or: [rst]
        stages: [manual]
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]

      - id: docs
        name: Build Documentation
        entry: uv run --extra=dev sphinx-build -M html docs/source docs/build -W
        language: python
        types_or: [rst]
        stages: [manual]
        pass_filenames: false
        additional_dependencies: [uv==0.9.5]
