ci:
  skip:
    - pyright-verifytypes

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char
      - id: rst-backticks
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/regebro/pyroma
    rev: "5.0.1"
    hooks:
      - id: pyroma
        args: ["--min=10", "."]
  - repo: local
    hooks:
      - id: pyright-verifytypes
        name: pyright verifytypes
        entry: uv run pyright --ignoreexternal --verifytypes openapi_mock
        language: system
        pass_filenames: false
