---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        hook-stage: [pre-commit, pre-push, manual]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'

      - name: Lint
        shell: bash
        run: uv run --extra=dev prek run --all-files --hook-stage ${{ matrix.hook-stage }}
          --verbose

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

  completion-lint:
    needs: lint
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check lint job status
        run: |-
          if [ "${{ needs.lint.result }}" != "success" ]; then
            echo "Lint job failed"
            exit 1
          fi
